#!/bin/fish

function gish_status
    git status
    echo
    git log --oneline -n 5
end

gish_status

while true
    read --shell -P '> ' -c 'git ' -l input
    if test $status -ne 0 || test $input = ""
        break
    end

    if test $input = "git "
        gish_status
        continue
    end

    eval "$input"
 end
